# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-4cbc6029-cc46-40c0-aeee-f59f2effb5d2";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-4cbc6029-cc46-40c0-aeee-f59f2effb5d2".device = "/dev/disk/by-uuid/4cbc6029-cc46-40c0-aeee-f59f2effb5d2";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D072-A19A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/luks-c862bc1f-ecf7-42a9-8f78-4866ded9f041";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-c862bc1f-ecf7-42a9-8f78-4866ded9f041".device = "/dev/disk/by-uuid/c862bc1f-ecf7-42a9-8f78-4866ded9f041";

  swapDevices =
    [ { device = "/dev/mapper/nvme0n1p9_crypt"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
