[font]
size = 11.5
builtin_box_drawing = true

#  normal = { family = "FiraCode Nerd Font", style = "Regular" }
#  bold = { family = "FiraCode Nerd Font", style = "Bold" }
#  italic = { family = "FiraCode Nerd Font Propo", style = "Regular" }
#  bold_italic = { family = "FiraCode Nerd Font Propo", style = "SemiBold" }

#normal = { family = "Mononoki Nerd Font Mono", style = "Regular" }
#normal = { family = "UbuntuSansMono Nerd Font", style = "Regular" }
#normal = { family = "JetBrainsMono NF", style = "Regular" }
#normal = { family = "Hack Nerd Font", style = "Regular" }
normal = { family = "Maple Mono NF", style = "Regular" }
